name: mir-kiosk-osk 
base: core18
version: '0.1'
summary: A demonstration of on screen keyboard with mir
description: |
  This is a demo snap to showcase multiple app running and using
  a common on screen keyboard.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


layout:
  /usr/share:
    bind: $SNAP/usr/share
  /usr/lib/at-spi2-core:
    bind: $SNAP/usr/lib/at-spi2-core
  /etc/xdg:
    bind: $SNAP/etc/xdg


apps:
  window-manager:
    command: desktop-launch $SNAP/bin/launcher.sh $SNAP/bin/launchterm #xwayland-dashkiosk-launch # chromium.launcher
    daemon: simple
    environment:
      XWAYLAND_I3_CONFIG_FILE: $SNAP/i3.config
    slots: [ x11 ]
    plugs:
      - avahi-observe
      - browser-support
      - hardware-observe
      - home
      - mount-observe
      - network
      - network-bind
      - network-manager
      - opengl
      - password-manager-service
      - process-control
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - wayland
      - x11-plug

plugs:
  x11-plug:
    interface: x11
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  # gnome-3-28-1804:
  #   interface: content
  #   target: $SNAP/gnome-platform
  #   default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes


# slots:
#   dbus-daemon:
#     interface: dbus
#     bus: session
#     # name: org.onboard.Onboard
#     name: org.freedesktop.Dbus


parts:

  # Helper to run X11 applications on a Wayland kiosk
  # using the Xwayland and a basic window manager to 
  # enforce full screen kiosk behavior
  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]


  # X11 Window Manager
  wmx:
    after: [ xwayland-kiosk-helper ]
    source: http://www.all-day-breakfast.com/wmx/wmx-8.tar.gz
    plugin: nil
    override-build: |
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      # enable clock
      sed -i 's/#define CONFIG_CLOCK.\{14\}False/#define CONFIG_CLOCK\t\t  True/' Config.h
      # set our own cursor
      sed -i 's/#define CONFIG_USE_PLAIN_X_CURSORS\tTrue/#define CONFIG_USE_PLAIN_X_CURSORS\tFalse/' Config.h
      # change terminal command
      sed -i 's/x-terminal-emulator/launchterm/' Config.h
      # rename "New" to "New Terminal"
      sed -i 's/\"New\"/\"New Terminal\"/' Config.h
      # swich default font
      sed -i 's/Bitstream Vera Sans/DejaVu Sans/' Config.h
      # drop useless chown
      sed -i 's/-chown/#-chown/' Makefile
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      make install

    build-packages:
      - libfontconfig1-dev
      - libice-dev
      - libsm-dev
      - libx11-dev
      - libxau-dev
      - libxcb1-dev
      - libxcomposite-dev
      - libxdmcp-dev
      - libxext-dev
      - libxft-dev
      - libxpm-dev
      - libxrender-dev
      - xfonts-utils
    stage-packages:
      - busybox-static
      - bsdutils
      - dropbear-bin
      - fontconfig
      - fonts-dejavu-core
      - libsm6
      - libice6
      - libx11-6
      - libxau6
      - libxcomposite1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxpm4
      - libxrender1
      - libfontconfig1
      - libxcb1
      - rxvt-unicode
      - xfonts-75dpi
      - xfonts-100dpi
      - xfonts-base
      - xfonts-scalable
      - xfonts-unifont
      - x11-apps
      - x11-xserver-utils
      - dbus-x11


  # X11 Fonts
  x11fonts:
    plugin: nil
    after: [ wmx ]
    override-prime: |
      for dir in X11/misc X11/Type1 X11/75dpi X11/100dpi truetype/dejavu; do
        cd usr/share/fonts/$dir
        mkfontscale
        mkfontdir
        cd - >/dev/null
      done
      snapcraftctl prime

  # Scripts to start wmx
  scripts:
    plugin: dump
    source: scripts

  # This is list of on screen keyboards
  osk-list:
    plugin: nil
    stage-packages:
      - xvkbd
      - matchbox-keyboard
      - onboard
      - florence
      - at-spi2-core
      - python-gobject


  gtk-packs:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - libgtk2.0-0
